#!/usr/bin/perl
# vim: ft=perl:
use strict;
use Term::ExtendedColor::Xresources qw(get_xterm_color);
use Getopt::Long;


output();

sub output {
  my $c = get_xterm_color(
    {
      index => [0 .. 255],
      type  => 'hex',
    }
  );

  open(my $fh, '>', "$0.html") or die $!;
  select $fh;

  print '<h1><font color="#999">Read xterm configuration</font></h1>';
  print '<body bgcolor="#121212">';

  for my $index( sort { $a <=> $b } keys %{ $c } ) {
    printf(qq(<h2>%s <font color="#888">#</font>%s</h2>),
      qq(<font color="#$c->{ $index }->{rgb}">$index</font>),
      qq(<font color="#$c->{ $index }->{rgb}">$c->{ $index }->{rgb}),
    );
  }
  print "</body></html>\n";
}
